version: '3.8'

services:
  mork-biocypher:
    build: .
    container_name: mork-biocypher
    ports:
      - "8027:8027"
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8027/status/-"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
  reports: